### ISSUE TITLE
how to convert custom jalaali date time to utc time

### ISSUE THREAD

**Issue by shahryarjb** [jalaali/elixir-jalaali#10]
Hello , I have a string like this "1398-05-21 10:03:04" , now how can I convert this to utc_time like this`DateTime.utc_now` output.

Thanks

**Comment by shahryarjb** [comment]
I created a way but I think there is a better way for this
```elixir
  def jalali_string_to_miladi_english_number(persian_string_time_number) do
    [yy, mm, dd] = String.split(persian_string_time_number, "/")
    {:ok, jalaali_date} = Date.new(Numero.normalize_as_number!(yy), Numero.normalize_as_number!(mm), Numero.normalize_as_number!(dd), Jalaali.Calendar)
    {:ok, iso_date} = Date.convert(jalaali_date, Calendar.ISO)
    {:ok, datetime, 0} = DateTime.from_iso8601("#{iso_date.year}-#{fix_month_and_day(iso_date.month)}-#{fix_month_and_day(iso_date.day)}T00:00:00Z")
    datetime
  end

  def fix_month_and_day(string_number) do
    if String.length("#{string_number}") == 1 do
      "0#{string_number}"
    else
      "#{string_number}"
    end
  end
```

All the Persian calendar backs a farsi numbers, at first I converted it and make to whatever I need, do you have an idea better than it?

**Comment by alisinabh** [comment]
Hi @shahryarjb.

You can use `NaiveDateTime.from_iso8601/2` for converting standard timezone-less string DateTimes.

## Example

```elixir
{:ok, datetime} = NaiveDateTime.from_iso8601 "1398-05-21 10:03:04", Jalaali.Calendar
```

**Comment by shahryarjb** [comment]
@alisinabh Thank you, but this code is about converting Normal calendar to Jalaali, I need to convert Jalaali to Normal

for example if when we need to convert it to jalaali we can use this:

```
iex(7)> NaiveDateTime.from_iso8601("2015-01-23 23:50:07", Jalaali.Calendar)
{:ok,
 %NaiveDateTime{
   calendar: Jalaali.Calendar,
   day: 3,
   hour: 23,
   microsecond: {0, 0},
   minute: 50,
   month: 11,
   second: 7,
   year: 1393
 }}
```

but when we  need to convert it (Jalaali) to (MILADI Gregorian), what is it solution?
for example I changed it to 1398
```
{:ok,
 %NaiveDateTime{
   calendar: Jalaali.Calendar,
   day: 4,
   hour: 23,
   microsecond: {0, 0},
   minute: 50,
   month: 11,
   second: 7,
   year: 776
 }}
```
it is wrong.

**Comment by shahryarjb** [comment]
@alisinabh Thank you, but this code is about converting Normal calendar to Jalaali, I need to convert Jalaali to Normal

for example if when we need to convert it to jalaali we can use this:

```
iex(7)> NaiveDateTime.from_iso8601("2015-01-23 23:50:07", Jalaali.Calendar)
{:ok,
 %NaiveDateTime{
   calendar: Jalaali.Calendar,
   day: 3,
   hour: 23,
   microsecond: {0, 0},
   minute: 50,
   month: 11,
   second: 7,
   year: 1393
 }}
```

but when we  need to convert it (Jalaali) to (MILADI Gregorian), what is its solution?
for example I changed it to 1398
```
{:ok,
 %NaiveDateTime{
   calendar: Jalaali.Calendar,
   day: 4,
   hour: 23,
   microsecond: {0, 0},
   minute: 50,
   month: 11,
   second: 7,
   year: 776
 }}
```
it is wrong.

**Comment by alisinabh** [comment]
Sorry i didn't know NaiveDateTime.from_iso8601 will convert to the calendar **after** it parses the datetime. My bad.

Instead (for now) you can convert it like this:

```elixir
{:ok, datetime} = NaiveDateTime.from_iso8601("1398-01-31 23:50:07")
datetime = %{datetime | calendar: Jalaali.Calendar}
```

Beware that this is not tested and might not work in all situations. I don't know if this behavior of the NaiveDateTime's from_iso8601 function is expected or not.

**Comment by shahryarjb** [comment]
@alisinabh  thank you very much, this code can't help me because I can't convert it to normal calendar, it cals itself to Jalaali not  (Gregorian normal calendar) it is a Jalaali calendar still.

```elixir
{:ok, datetime} = NaiveDateTime.from_iso8601("1398-01-31 23:50:07")
{:ok, ~N[1398-01-31 23:50:07]}
iex(13)> datetime = %{datetime | calendar: Jalaali.Calendar}
%NaiveDateTime{
  calendar: Jalaali.Calendar,
  day: 31,
  hour: 23,
  microsecond: {0, 0},
  minute: 50,
  month: 1,
  second: 7,
  year: 1398
}
```


 but I think I should get the time which I need in different field or form singly and then I can merge with my code

```elixir
  def jalali_string_to_miladi_english_number(persian_string_time_number) do
    [yy, mm, dd] = String.split(persian_string_time_number, "/")
    {:ok, jalaali_date} = Date.new(Numero.normalize_as_number!(yy), Numero.normalize_as_number!(mm), Numero.normalize_as_number!(dd), Jalaali.Calendar)
    {:ok, iso_date} = Date.convert(jalaali_date, Calendar.ISO)
    {:ok, datetime, 0} = DateTime.from_iso8601("#{iso_date.year}-#{fix_month_and_day(iso_date.month)}-#{fix_month_and_day(iso_date.day)}T00:00:00Z")
    datetime
  end
```
I can replace the fake time with my real time.
```
T00:00:00Z to ===> real time the user imports
```

If you have a better idea, would you mind telling me pleas?

**Comment by alisinabh** [comment]
Sorry @shahryarjb, I'm not quite sure what is your goal here. 

If your problem is to parse a datetime string like `1398-05-21 10:03:04` and convert it to gregorian (milaadi) then this will do the job.

```elixir
{:ok, jalaali_datetime} = NaiveDateTime.from_iso8601("1398-01-31 23:50:07")
jalaali_datetime = %{jalaali_datetime | calendar: Jalaali.Calendar}
{:ok, gregorian_datetime} = NaiveDateTime.convert(jalaali_datetime, Calendar.ISO)
NaiveDateTime.to_string(gregorian_datetime)
```

If this is not your goal, Please do explain what do you want to achieve.

Thanks.

**Comment by shahryarjb** [comment]
@shahryarjb, Thank you Thank you Thank you, I needed this what you wrote. I hope it works in all situations, it would better if you add this code in Jalaali document.

Thanks.
