### ISSUE TITLE
Is there a plan to add some features to next version?

### ISSUE THREAD

**Issue by shahryarjb** [jalaali/elixir-jalaali#14]
Hello maintainer, 
I have a question which is “Is there a plan to add some features to next version?”  or any way to improve this lib to keep it fresh?
I am going to create a new calendar UI with phoenix LiveView with your library help, but I am still interested on updating this project.
Thanks

**Comment by alisinabh** [comment]
Hello @shahryarjb,

Currently I don't have anything in mind but suggestions and ideas are welcome.
