### ISSUE TITLE
`dialyxir` should be updated for elixir 1.15

### ISSUE THREAD

**Issue by shahryarjb** [jalaali/elixir-jalaali#21]
Dear @alisinabh,
We have a compile dependency error when we are in Elixir 1.15 and OTP 26, This error is because the `dialyxir` version has not been updated. I don't know if this will cause us to lose support for older versions.

I tested `{:dialyxir, "~> 1.3", only: [:dev, :test], runtime: false}` version and it does not need to use `--force`

Thank you

**Comment by alisinabh** [comment]
Fixed in #22. Thanks for the report. 💜
