### ISSUE TITLE
Adapt with new Calendar behaviour

### ISSUE THREAD

**Issue by alisinabh** [jalaali/elixir-jalaali#5]
Since calendar behaviour may change. this library will have to completely change its interface to use calendar behaviour.

**Comment by alisinabh** [comment]
Elixir 1.5.0-rc1 is released.

Work on this issue will be started soon...

**Comment by shahryarjb** [comment]
hi @alisinabh . thank you for releasing elixir jalali calendar .
When do you release new version to support elixir 1.5 ?

**Comment by alisinabh** [comment]
Hey @shahryarjb.

The implementation is almost done. I just need some time to implement tests.
I think it will be delivered next week.

Any suggestions or co-operation is appreciated.

Thanks

**Comment by alisinabh** [comment]
@shahryarjb v0.2.0 is here supporting Elixir Calendar ecosystem.
